Test push for pull request
InoHanabishi/ETL pull request #1
Opened 2022-08-26 15:44 UTC by InoHanabishi

Awaiting code review for merger to master

2022-08-26 23:35 UTC, RDoll-Repo requested changes
I can see a lot of effort thus far has gone into UI here. I'm not trying to be overly pedantic here, but one thing to think about is that a lot of developers and teams choose to use VS Code, rather than Visual Studio as we were taught to use in school. This may not seem important, and you may be wondering why I'm even bothering to mention it. 

The reason is twofold:

1.) The major difference between Visual Studio Community/Enterprise/Professional/etc. and Visual Studio Code is that the former is an IDE, meaning it has all the bells and whistles required to make whatever you've coded compile. This is a great feature and certainly saved us a number of headaches in school. However, VS Code is simply an extensible code editor. When writing programs to publish to GH, it's important to make sure that anyone, regardless of rig is able to spin your project up and run it. If they can't do that in a reasonable amount of time, that's potential contributions and valuable review you could lose. So this has been a long diatribe to say that we need to consider VS Code users who don't have an IDE automatically generating these important files for them. As this PR stands, you cannot plug it into VS Code and run it. What you should do is supply these config files in your repo. My recommendation is to take a look at this article (I'm not sure if this is 100% the solution we want, but it should put you on the right track. 

https://www.c-sharpcorner.com/article/running-a-visual-studio-2019-solution-in-visual-studio-code/

and then consider installing VS Code yourself and testing to see if it works. It's also entirely possible that these files exist pre-made in Visual Studio and you could just yank them out and move them. Not super sure though. 

2.) The other reason that a lot of devs prefer VS Code is because you have more control over these config files among many other things. Not as much to say here. So I'll leave the review here for now, and once you get that in order, I'll be more than happy to re-review. 

Since we're learning and practicing PR flow here, I'd recommend not merging this PR in until I approve it. Not trying to like hijack your project or anything, just in a real-world setting, you'll usually have to get an approval from someone to merge, usually a teammate or a lead dev. I know this is a dense first review, so take it slow if you need to.

2022-08-30 15:57 UTC, InoHanabishi commented
re-request per our conversation.

2022-09-01 11:42 UTC, RDoll-Repo requested changes
One small change and then we can merge.

2022-09-01 11:42 UTC, RDoll-Repo commented on ETL/Main Form.Designer.cs
> +            this.btnDestination.Click += new System.EventHandler(this.btnDestination_Click);
This is auto-generated code that Visual Studio makes for us when we write forms applications. It may be worth the time to hop in here and figure out how this works so you can further customize its attributes and behavior. This isn't necessarily PR review, so don't feel like you've got to just hop in here and do stuff now.

2022-09-01 11:42 UTC, RDoll-Repo commented on ETL/Main Form.cs
> +			// Prepare a dummy string, thos would appear in the dialog
Typo in your comment. We want to be careful to be clear in our documentation. Hypothetically, if this were an enterprise project and you were to leave and have a new developer take over this project, we'd want his onboarding to the codebase be as smooth as possible.

2022-09-01 11:42 UTC, RDoll-Repo commented on ETL/Main Form.cs
> +				// Do whatever
Does `// Do whatever` mean that the actual saving logic is outside of the scope of this PR?

2022-09-01 12:55 UTC, InoHanabishi commented on ETL/Main Form.Designer.cs
> +            this.btnDestination.Click += new System.EventHandler(this.btnDestination_Click);
Have experience in dealing with these attributes for customization and debugging from capstone webapp and even creating my own problems here. It's the code that is generated from using toolbox objects and the settings we assign in the properties window.

2022-09-01 12:57 UTC, InoHanabishi commented on ETL/Main Form.cs
> +			// Prepare a dummy string, thos would appear in the dialog
Understood. Comment better and without typos. This section does not exist in the next commit. Destination button has been removed and converted file is placed in same directory as selected file.

2022-09-01 12:59 UTC, InoHanabishi commented on ETL/Main Form.cs
> +				// Do whatever
// do whatever, was an indication that logic needed to be added there. Per above reply, this section no longer exists as of next push.

2022-09-01 13:37 UTC, RDoll-Repo commented on ETL/Main Form.cs
> +				// Do whatever
That wasn't me telling you to remove it, it's totally fine that you had that there.

2022-09-01 13:40 UTC, RDoll-Repo commented on ETL/Main Form.Designer.cs
> +            this.btnDestination.Click += new System.EventHandler(this.btnDestination_Click);
What I'm getting at is that basically these toolbox features can sometimes write stupid code if you lean on them too heavily. All I mean to say is that as this project goes on, you may want to lean more on doing minor adjustments programatically.

2022-09-01 13:41 UTC, RDoll-Repo commented on ETL/Main Form.cs
> +			// Prepare a dummy string, thos would appear in the dialog
The typo is still there. You should re-request review AFTER the commit that addresses comments is pushed instead of telling me it will be in the next commit.

2022-09-01 19:41 UTC, RDoll-Repo approved these changes
Looks good. One final note on this PR, when naming files, we typically wanna omit spaces. Opt for a different approach like underscores, dashes, or camel case. Spaces make the files annoying to navigate in command line.

2022-09-01 19:41 UTC, merged